### ISSUE TITLE
No able to normalize

### ISSUE THREAD

**Issue by skptricks** [paularmstrong/normalizr#361] opened 2018-12-30 07:56 UTC
var originalData = {
  order: {
    id: 10,
    line_items: [
      {
        id: 483,
        quantity: 2,
        product: {
          id: 924,
          name: "Carrots",
          price: "1.50"
        }
      }
    ]
  },
  products: [
    {
      id: 924,
      name: "Carrots",
      price: "1.50"
    },
    {
      id: 9274,
      name: "Car",
      price: "1.50"
    }
  ]
};

**Comment by thib92** [comment] 2019-02-02 14:58
This is a duplicate of #362.

**Closed** 2019-02-04 04:19 UTC
