### ISSUE TITLE
Unexpected normalize behavior

### ISSUE THREAD

**Issue by johnryan** [paularmstrong/normalizr#319] opened 2018-01-26 18:26 UTC
# Problem

When normalizing an empty array it is dangerously easy to get undefined values. Is this intended? See example

**Input**

Here's how I'm using normalizr:

```js
const normalizr = require('normalizr');
const { schema, normalize } = normalizr;


const feedSchema = new schema.Entity(
  'feed',
  {
    idAttribute: object => object.entity.id
  }
);

const itemSchema = new schema.Entity(
  'items',
  {
    feed: [feedSchema]
  },
  {
    idAttribute: 'id'
  }
);

const listSchema = [itemSchema];

const stubData = [{
  id: "123",
  "feed": [{
    id: "456",
    name: "my feed item"
  }]
}]

normalize([], listSchema);
```

**Output**

Here's what I expect to see when I run the above:

```js
{
    result: [],
    entities: { 
       feed: {},
       items: {}
    }
}
```

Here's what I *actually* see when I run the above:

```js
{ entities: {}, result: [] }
```

The result of this is that every check to `schema.entities.feed['someId']` needs a check on `schema.entities.feed`. If this is the intended behavior that's fine, just wanted to point out that it seems like a bug to a new user. Thanks!

**Comment by paularmstrong** [comment] 2018-01-26 18:44
Duplicate of #290

**Closed by paularmstrong** 2018-01-26 18:44 UTC
