### ISSUE TITLE
denormalize doesn't handle circular references

### ISSUE THREAD

**Issue by andyhite** [paularmstrong/normalizr#236] opened 2017-02-10 20:52 UTC
# Problem

`denormalize` doesn't handle circular references, and throws a Maximum stack call size exceeded` error when it encounters one.

**Input**

Here's how I'm using normalizr:

```js
const schemaFoo = new schema.Entity('schemaFoos');
const schemaBar = new schema.Entity('schemaBars', { foo: schemaFoo });
schemaA.define({ bars: [schemaBars] });

const dataFoo = { id: 1 };
const dataBar = { id: 2, foo: dataFoo };
dataA.bars = [dataBar];

const normalizedFoo = normalize(dataFoo, schemaFoo);

denormalize(normalizedFoo, schemaFoo); // Maximum call stack size exceeded
```

**Output**

Here's what I expect to see when I run the above:

```js
{
  id: 1,
  bars: [{
    id: 2,
    foo: {
      id: 1,
      bars: [...]
    },
  }]
}
```

Optimally this would indeed return the circular references, turtles all the way down, but it could also work by specifying how deep to denormalize the data.

Here's what I *actually* see when I run the above:

```js
// Error: Maximum call stack size exceeded
```

**Comment by paularmstrong** [comment] 2017-02-10 21:03
Duplicate of #216. For now, you'll have to fix your schema that you're passing to denormalize to stop having circular references where applicable.

**Comment by andyhite** [comment] 2017-02-10 21:04
I don't know how I missed that...thanks.

**Closed by paularmstrong** 2017-02-10 21:03 UTC
