### ISSUE TITLE
Change in denormalize() behavior from 3.2.3 => 3.2.4 when passing objects as input

### ISSUE THREAD

**Issue by swieder227** [paularmstrong/normalizr#430] opened 2020-01-07 16:28 UTC
# Repro

Here's my repro case:
https://jsfiddle.net/sethwieder/L46en8b2/40/

### Expected
We're passing in an object as the input and expected it to denormalize nested objects based on the provided schema.

### Actual
The output duplicate the same item for each index in the input array.

# Context
This used to work in 3.2.3, but no longer works as of 3.2.4.

It's unclear to me if this is even correct usage of denormalize(), as the docs just say:
"the normalized result that should be de-normalized. Usually the same value that was given in the result key of the output of normalize." - is this expected to only work with IDs as inputs?

It's also unclear from the [tag changelog](https://github.com/paularmstrong/normalizr/compare/v3.2.3...v3.2.4) what exactly caused this change in behavior and if it's expected or not

**Comment by 3v0k4** [comment] 2021-07-05 10:11
@swieder227 thanks for filing this issue! You saved me hours of headaches!!

@paularmstrong Is there any chance this is considered a regression that can be fixed?

**Comment by ntucker** [comment] 2021-07-06 23:14
https://github.com/paularmstrong/normalizr/commit/ba1847bb859ae12a448e6175e0d0b4aca4e9249b is the commit that changed it. It seems to have simplified things by assuming ids as input. This does match expectations from my interpretation of the library. However, this probably should have been marked as a breaking change.

**Comment by paularmstrong** [comment] 2021-07-07 15:07
Confirming that this is expected. The values you're passing in are _partially_ normalized, but denormalization expects a fully normalized schema. 

I wouldn't have labeled this as a breaking change because it previously working was not an expectation and was never documented as such.

For the test case, you could change your schema to be `partiallyNormalizedPeople` as so:

```
// imports normalizr via the JSFiddle Resources panel.
// Testcase assertions fail in 3.2.4 but works in 3.2.3.
// https://unpkg.com/normalizr@3.2.4/dist/normalizr.browser.js
// https://unpkg.com/normalizr@3.2.3/dist/normalizr.umd.js
const denormalize = normalizr.denormalize;
const schema = normalizr.schema;

const foodSchema = new schema.Entity('foods');

const peopleSchema = new schema.Entity('people', {
	favoriteFoods: [foodSchema],
});

// USE THIS ⬇️
const partiallyNormalizedPeople = { favoriteFoods: [foodSchema] };

const entities = {
  'people': {
    0: {'id': 0, favoriteFoods: [777, 555]},
    1: {'id': 1, favoriteFoods: [333]},
    2: {'id': 2, favoriteFoods: [555]},    
  },
  'foods': {
    777: {'id': 777, name: 'Orange'},
    555: {'id': 555, name: 'Apple'},
    333: {'id': 333, name: 'Banana'}
  }
}

const testcase = denormalize(
  [
      {'id': 0, favoriteFoods: [777, 555]},
      {'id': 1, favoriteFoods: [333]},
      {'id': 2, favoriteFoods: [555]},    
  ],
  [partiallyNormalizedPeople],
  entities
);
```

**Closed by paularmstrong** 2021-07-07 15:07 UTC
