### ISSUE TITLE
Performance with large datasets

### ISSUE THREAD

**Issue by abesiemsen** [paularmstrong/normalizr#432] opened 2020-01-23 16:25 UTC
Hi Paul, my issue is definitely of a 'does this make sense to you?' nature, rather than 'I found a bug.' I'm experiencing something very similar to the question asked in issue #263. 

The dataset I'm trying to normalize is very large: an array of ~6500 records, each record having ~500 lines worth of nested sub-items. Total data size of the stringified JSON is ~25MB, so an order of magnitude more data that described in #263. Clearly, I'm asking a lot.

That said, my normalization time for this data is **REALLY** long. 90+ seconds. So I'm comparing my performance with #263, and it breaks down like this:

2000 records * 50 lines/record in 170ms = ~1.7ms / 1k lines of data.
6500 records * 500 lines/record in 90000ms = 27.7ms / 1k lines of data.

**Any idea what might account for such a significant disparity in processing time?**

Thanks Paul -- I appreciate what a great tool normalizr is!

For reference, here's the schema I'm passing to the normalize function:

```
itemSchema = new schema.Entity(
  'contacts',
  {
    firm: new schema.Entity(
      'firms',
      {image: new schema.Entity('images')}
    ),
    image: new schema.Entity('images'),
    created_by: new schema.Entity(
      'users',
      {image: new schema.Entity('images')}
    ),
    company_links: new schema.Array(new schema.Entity(
      'companyContactLinks',
      {
        company: new schema.Entity(
          'companies',
          {
            affiliation: new schema.Entity('companyAffiliations'),
            image: new schema.Entity('images'),
            industry_links: new schema.Array(new schema.Entity(
              'industryLinks',
              {industry: new schema.Entity('industries')},
              {processStrategy: (value, parent, key) => ({...value, company: parent.id})}
            ))
          }
        ),
        interior_roles: new schema.Array(new schema.Entity(
          'companyContactInteriorCompanyRoleLinks',
          {interior_company_role: new schema.Entity('interiorCompanyRoles')},
          {processStrategy: (value, parent, key) => ({...value, company_contact_link: parent.id})}
        )),
        exterior_roles: new schema.Array(new schema.Entity(
          'companyContactExteriorCompanyRoleLinks',
          {exterior_company_role: new schema.Entity('exteriorCompanyRoles')},
          {processStrategy: (value, parent, key) => ({...value, company_contact_link: parent.id})}
        ))
      },
      {processStrategy: (value, parent, key) => ({...value, contact: parent.id})}
    )),
    primary_company_contact_link: new schema.Entity(
      'companyContactLinks',
      {
        company: new schema.Entity(
          'companies',
          {
            affiliation: new schema.Entity('companyAffiliations'),
            image: new schema.Entity('images'),
            industry_links: new schema.Array(new schema.Entity(
              'industryLinks',
              {industry: new schema.Entity('industries')},
              {processStrategy: (value, parent, key) => ({...value, company: parent.id})}
            ))
          }
        ),
        interior_roles: new schema.Array(new schema.Entity(
          'companyContactInteriorCompanyRoleLinks',
          {interior_company_role: new schema.Entity('interiorCompanyRoles')},
          {processStrategy: (value, parent, key) => ({...value, company_contact_link: parent.id})}
        )),
        exterior_roles: new schema.Array(new schema.Entity(
          'companyContactExteriorCompanyRoleLinks',
          {exterior_company_role: new schema.Entity('exteriorCompanyRoles')},
          {processStrategy: (value, parent, key) => ({...value, company_contact_link: parent.id})}
        ))
      }
    ),
    tag_links: new schema.Array(new schema.Entity(
      'contactTagLinks',
      {tag: new schema.Entity('tags')},
      {processStrategy: (value, parent, key) => ({...value, contact: parent.id})}
    ))
  }
);

listSchema = new schema.Array(this.itemSchema);
```

**Comment by paularmstrong** [comment] 2020-01-23 16:45
duplicate of #383

**Closed by paularmstrong** 2020-01-23 16:45 UTC

**Comment by abesiemsen** [comment] 2020-01-23 16:47
Of course, after posting this I found once part of the problem: using the spread operator in my `processStrategy` functions. By changing from
```
{processStrategy: (value, parent, key) => ({...value, company: parent.id})}
```
to
```
{processStrategy: (value, parent, key) => {
  value.company = parent.id;
  return value;
}}
```
I've cut total processing time to 22seconds(!), so now my comparison to #263 looks like this:

2000 records * 50 lines/record in 170ms = ~1.7ms / 1k lines of data.
6500 records * 500 lines/record in 22000ms = ~6.8ms / 1k lines of data.

Still curious if this feels 'expected' to you, or whether you have any thoughts about other things that might affect performance.

**Comment by abesiemsen** [comment] 2020-01-23 17:22
Reverting to 3.3.0 made an absolutely astoundingly improved difference!
