### ISSUE TITLE
Denormalized data reference to shallow copy

### ISSUE THREAD

**Issue by Serenya** [paularmstrong/normalizr#235] opened 2017-02-10 18:47 UTC
I don't know if it is intentionally done, but after calling denormalize method, objects which have same id reference to a different object. Most probably they are being shallow copied, see denormalize method https://github.com/paularmstrong/normalizr/blob/master/src/schemas/Entity.js

An example: 
```javascript
import { denormalize, schema } from 'normalizr';

const mentor = new schema.Entity('mentors');
const user = new schema.Entity('users', {
  mentor: mentor
});

const mySchema = { users: [ user ] }
const entities = { users: { '1': { id: 1, mentor: 3 }, '2': { id: 2, mentor: 3 } , mentors: { '3': { id: 3, name: 'John' } } } };
const denormalizedData = denormalize({ users: [ 1, 2 ] }, mySchema, entities);
console.log(denormalizedData.users[0].mentor === denormalizedData.users[1].mentor)
```

Output: false

I am expecting to get 'true' as it was in original data before it was normalized.

**Comment by paularmstrong** [comment] 2017-02-10 21:02
Duplicate of #233. Fixed in v2.3.1

**Closed by paularmstrong** 2017-02-10 21:02 UTC

**Comment by Serenya** [comment] 2017-02-10 21:32
Paul,

sorry for the not working code (wrong braces order), that had to show the actual problem. This should definitely work:
```javascript
const mentor = new schema.Entity('mentors');
const user = new schema.Entity('users', {
   mentor: mentor
});

const mySchema = { users: [ user ] }
const entities = { users: { '1': { id: 1, mentor: 3 }, '2': { id: 2, mentor: 3 } }, mentors: { '3': { id: 3, name: 'John'  } } };
const denormalizedData = denormalize({ users: [ 1, 2 ] }, mySchema, entities);
console.log(denormalizedData.users[0].mentor === denormalizedData.users[1].mentor);
```
The output of comparing two mentor objects, which, if I understand it correctly, should be equal by the reference. But they are equal only by the values of theirs properties.

This issue is not a duplicate of https://github.com/paularmstrong/normalizr/issues/233 because not we are dealing with objects and not with theirs keys.

**Comment by paularmstrong** [comment] 2017-02-10 21:36
Sorry, went a little fast there... This is the intended behavior. We return copies of all entities because otherwise denormalization will may the originals.

**Comment by Serenya** [comment] 2017-02-11 07:51
Thank you for the quick feedback. I think it does make sense to make shallow copy of the root objects, but why would we make copies of child objects? If the purpose is to sustain original normalized data, then it does make sense to use https://github.com/sasaplus1/deepcopy.js library for entities to not modify them. I feel that expected behavior of the denormalize function should be the output same as the input of the normalize function. In example below original data(non-normalized) had the same references to 'mentor' objects in two different users and it should have the same references to 'mentor' objects in two different users after calling denormalize functoin.

**Comment by Serenya** [comment] 2017-02-19 21:27
@paularmstrong could you please give comments regards to my previous post? Thanks.

**Comment by ShirleyYoung0926** [comment] 2017-06-26 09:56
In our project, we use normalize to store data in entities. When we want to get the origin data to render component, we use denormalize to get the origin data. But, because it returns a new object everytime, the component will rendered again and again. So, how can we get the original data without causing unnecessary render?

**Comment by paularmstrong** [comment] 2017-06-26 20:19
@ShirleyYoung0926 use [reselect](https://github.com/reactjs/reselect) (or similar) and [shouldComponentUpdate](https://facebook.github.io/react/docs/react-component.html#shouldcomponentupdate)
