### ISSUE TITLE
How to migrate from 2.x.x to 3.x.x?

### ISSUE THREAD

**Issue by itinance** [paularmstrong/normalizr#221] opened 2017-01-14 14:58 UTC
Having code like this from former versions 2.x.x.:

```
export const userSchema = new Schema('users', {idAttribute: 'id'});
```   
```   
const usersData = yield call( ... loading data ... );

const users = normalize(usersData, arrayOf(userSchema));
```   

Since arrayOf was removed in 3.x.x, how to migrate this piece of code to v3? Couldn't find any HowTo's ...

I tried to use 

`schema.Array( 'users', [ schema.Entity('users', {idAttribute: 'id'}) ]`

but this gives another result as the arrayOf-Implementation. "entities" would be an empty array and result contains not only the IDs but all the objects, that was placed within "entities" in 2.x.

**Comment by paularmstrong** [comment] 2017-01-14 20:12
Duplicate of gh-215

**Closed by paularmstrong** 2017-01-14 20:12 UTC
