### ISSUE TITLE
Immutable input for denormalize?

### ISSUE THREAD

**Issue by babsonmatt** [paularmstrong/normalizr#241] opened 2017-02-23 02:25 UTC
# Problem

I'd like to be able to pass in an immutable object as input to denormalize.  Right now I'd have to call .toJS() on event when I pass it in to denormalize as input, it'd be nice to be able to avoid this.  

**Input**

Here's how I'd like to use denormalize:

```js
const Immutable = require('immutable');
const Normalizr = require('normalizr');
const { denormalize, schema } = Normalizr;

const ticket = new schema.Entity('tickets');
const eventSchema = { 
  tickets: [ ticket ]
}

const event = Immutable.fromJS({
  id: 1,
  title: 'test event',
  tickets: [1, 2],
});

const entities = Immutable.fromJS({
  tickets: {
    1: {
      id: 1,
      title: 'ticket 1'
    },
    2: {
      id: 2,
      title: 'ticket 2'
    }
  }
});

const denormalizedData = denormalize(event, eventSchema, entities);

console.log(denormalizedData);
```

**Output**

Here's what I expect to see when I run the above:

```js
Map {
  "id": 1,
  "title": "test event",
  "tickets": List [
     Map { "id": 1, "title": "ticket 1" },
     Map { "id": 2, "title": "ticket 2" }
  ]
}
```

Here's what I *actually* see when I run the above:

```js
Map { "id": 1, "title": "test event", "tickets": List [ 1, 2 ] }
```

**Comment by paularmstrong** [comment] 2017-02-23 16:01
This is a problem that's been pointed out regarding Immutable Lists only. I'm not too familiar with Immutable, so a PR would be greatly appreciated.

**Comment by paularmstrong** [comment] 2017-02-23 16:07
Duplicate of #240

**Closed by paularmstrong** 2017-02-23 16:07 UTC
Labels: Priority: High, Type: Bug
